var namespacevari =
[
    [ "_uvptr", "classvari_1_1__uvptr.html", "classvari_1_1__uvptr" ],
    [ "_uvref", "structvari_1_1__uvref.html", "structvari_1_1__uvref" ],
    [ "_vptr", "classvari_1_1__vptr.html", "classvari_1_1__vptr" ],
    [ "_vref", "classvari_1_1__vref.html", "classvari_1_1__vref" ],
    [ "def_del", "structvari_1_1def__del.html", null ],
    [ "typelist_compatible", "conceptvari_1_1typelist__compatible.html", null ],
    [ "nothrow_three_way_comparable", "conceptvari_1_1nothrow__three__way__comparable.html", null ],
    [ "nothrow_equality_comparable", "conceptvari_1_1nothrow__equality__comparable.html", null ],
    [ "invocable", "conceptvari_1_1invocable.html", null ],
    [ "_forward_nothrow_constructible", "conceptvari_1_1__forward__nothrow__constructible.html", null ],
    [ "invocable_for_one", "conceptvari_1_1invocable__for__one.html", null ],
    [ "invocable_with_any", "conceptvari_1_1invocable__with__any.html", null ],
    [ "vconvertible_to", "conceptvari_1_1vconvertible__to.html", null ],
    [ "vconvertible_type", "conceptvari_1_1vconvertible__type.html", null ],
    [ "copy_constructible_deleter", "conceptvari_1_1copy__constructible__deleter.html", null ],
    [ "move_constructible_deleter", "conceptvari_1_1move__constructible__deleter.html", null ],
    [ "convertible_deleter", "conceptvari_1_1convertible__deleter.html", null ],
    [ "_define_variadic", "namespacevari.html#aa40348ea19f55b6deeba5d4ab2adcead", null ],
    [ "uvptr", "namespacevari.html#a3be05c6f854dc1b903a2a85e244bbdc5", null ],
    [ "uvref", "namespacevari.html#a2388c0eb42106efee2d8ed10243b69a0", null ],
    [ "vptr", "namespacevari.html#a50c11a69a9d782e1ccaa6ebd7be73725", null ],
    [ "vref", "namespacevari.html#a0b711b10138e06f9d5b455ff55c663d0", null ],
    [ "uwrap", "namespacevari.html#a4ebcd20c8226cf02de56c175cd7fdac6", null ]
];