name: clang-tidy

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: sudo apt install ninja-build libgtest-dev ccache clang-tidy-15

    - run: make configure

    - run: make clang-tidy
      if: false # temporarly disabled
