name: test

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              submomules: 'true'

          - name: install deps
            run: sudo apt install ninja-build ccache

          - name: configure
            run: make configure SANITIZER=address

          - name: build
            run: make build

          - name: test
            run: make test
